In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('ndim.csv')

In [3]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [4]:
df.head(5)

,starting_date,f1,auc,pr1,pr2,pr5,pr10,re1,re2,re5,re10,rev1,rev2,rev5,rev10,model,epoch,dim,lr,l2,beta,heads,fusion,activation,ntree,ndepth
0,13-01-01,0.200362,0.725739,0.324774,0.202568,0.105556,0.064462,0.144932,0.180762,0.235474,0.287605,0.243606,0.304403,0.361951,0.442793,DATE_13-01-01_25_2,5,16,0.005,0.01,0.0,4,concat,relu,25,2
1,13-01-01,0.570347,0.894151,0.913562,0.563676,0.256715,0.142816,0.407682,0.502905,0.572305,0.637185,0.374841,0.508252,0.615096,0.679045,DATE_13-01-01_25_6,5,16,0.005,0.01,0.0,4,concat,relu,25,6
2,13-01-01,0.582827,0.878212,0.932007,0.539631,0.241948,0.136112,0.415913,0.481278,0.539542,0.607166,0.353921,0.456848,0.571749,0.653211,DATE_13-01-01_25_5,5,16,0.005,0.01,0.0,4,concat,relu,25,5
3,13-01-01,0.194954,0.732588,0.338816,0.208469,0.106070,0.063450,0.149613,0.185926,0.236604,0.283086,0.217753,0.289898,0.352255,0.431730,DATE_13-01-01_25_2,5,16,0.005,0.01,0.0,4,concat,relu,25,2
4,13-01-01,0.465237,0.855401,0.742134,0.458853,0.214239,0.123359,0.331181,0.409458,0.477889,0.550355,0.272921,0.358577,0.459030,0.569235,DATE_13-01-01_25_3,5,16,0.005,0.01,0.0,4,concat,relu,25,3

In [5]:
df.groupby(['ndim'])['re1'].apply(len)

ntree  ndepth
25     2         10
       3         10
       4         10
       5         10
       6         10
50     2         10
       3         10
       4         10
       5         10
       6         10
100    2         10
       3         10
       4         10
       5         10
       6         10
200    2         10
       3         10
       4         10
       5         10
       6         10
400    2         10
       3         10
       4         10
       5         10
       6         10
Name: re1, dtype: int64

In [6]:
df.groupby(['ndim'])['f1','auc','pr1','pr2','pr5','pr10','re1','re2','re5','re10','rev1','rev2','rev5','rev10'].apply(lambda x: round(100 * np.mean(x), 2))

                 f1    auc    pr1    pr2    pr5   pr10    re1    re2    re5  \
ntree ndepth
25    2       19.76  72.94  32.48  20.10  10.51   6.46  14.46  17.93  23.44
      3       45.52  85.11  73.67  44.08  21.20  12.19  32.84  39.32  47.23
      4       53.13  86.34  86.24  49.60  22.72  12.71  38.45  44.20  50.66
      5       58.01  87.87  93.40  54.38  24.23  13.52  41.67  48.49  54.04
      6       58.09  89.36  92.31  56.59  25.62  14.39  41.16  50.49  57.15
50    2       53.97  87.50  87.79  51.22  23.84  13.32  39.12  45.65  53.14
      3       59.37  89.24  91.22  57.50  25.72  14.46  40.67  51.28  57.37
      4       63.68  92.27  90.51  66.71  30.38  16.45  40.25  59.45  67.76
      5       62.14  92.63  92.77  64.18  30.03  16.74  41.39  57.21  66.99
      6       64.08  93.95  92.97  67.45  32.18  17.71  41.46  60.16  71.72
100   2       74.58  95.72  92.62  79.03  36.35  19.28  41.14  70.39  81.03
      3       75.84  96.65  93.03  81.61  38.41  20.13  41.52  72.82  85.68
      4       75.53  96.80  93.13  80.79  38.67  20.22  41.49  72.09  86.26
      5       72.56  96.80  92.51  80.14  38.31  20.24  41.28  71.50  85.46
      6       72.85  96.35  95.71  78.29  37.75  19.96  42.70  69.86  84.20
200   2       78.04  96.72  92.54  83.23  38.55  20.15  41.29  74.27  85.99
      3       76.43  96.67  92.05  81.76  38.50  20.25  41.07  72.95  85.89
      4       73.62  96.09  93.62  79.31  37.74  19.89  41.78  70.73  84.20
      5       72.79  96.50  95.48  80.44  37.76  19.94  42.61  71.78  84.24
      6       71.03  96.26  96.59  79.46  37.20  19.72  43.10  70.90  82.98
400   2       76.55  96.76  93.69  82.14  38.72  20.25  41.79  73.26  86.38
      3       74.51  96.22  94.46  79.92  37.53  19.83  42.15  71.32  83.72
      4       73.58  96.41  94.77  79.34  37.64  19.97  42.29  70.79  83.96
      5       74.18  96.89  96.95  80.37  38.22  20.24  43.27  71.71  85.24
      6       72.16  96.80  96.33  81.96  38.20  20.18  42.98  73.13  85.21

               re10   rev1   rev2   rev5  rev10
ntree ndepth
25    2       28.81  22.85  28.51  36.17  44.50
      3       54.35  27.83  35.64  44.93  55.17
      4       56.70  31.25  40.65  50.48  60.90
      5       60.29  35.03  45.91  56.95  66.36
      6       64.18  38.03  51.45  61.38  70.69
50    2       59.40  35.00  47.17  58.02  67.43
      3       64.43  38.81  53.07  61.76  71.56
      4       73.40  42.71  61.25  74.07  80.58
      5       74.64  39.70  58.20  72.51  81.44
      6       79.03  41.04  60.51  76.04  83.75
100   2       86.00  44.57  66.46  81.05  87.08
      3       89.80  47.03  68.64  83.55  88.77
      4       90.20  44.84  66.31  83.45  89.30
      5       90.28  44.55  67.93  81.73  88.32
      6       89.04  38.87  64.78  79.51  86.35
200   2       89.87  46.23  68.12  84.08  89.54
      3       90.33  47.10  68.20  82.13  88.92
      4       88.74  40.65  63.89  78.19  84.15
      5       88.96  40.27  66.37  79.64  85.92
      6       87.97  37.61  62.56  76.94  84.66
400   2       90.35  45.04  69.11  84.32  89.50
      3       88.46  43.90  66.28  79.15  85.79
      4       89.11  38.25  63.03  77.75  84.58
      5       90.29  35.87  63.26  79.41  86.29
      6       90.05  37.63  64.71  79.63  88.02

In [18]:
df.groupby(['ndim'])['f1','auc','pr1','pr2','pr5','pr10','re1','re2','re5','re10','rev1','rev2','rev5','rev10'].apply(lambda x: round(100 * np.std(x), 2))

                f1   auc   pr1   pr2   pr5  pr10   re1   re2   re5  re10  \
ntree ndepth
25    2       0.42  0.49  0.77  0.51  0.12  0.08  0.31  0.45  0.28  0.33
      3       1.48  0.41  2.64  1.05  0.43  0.20  1.17  0.93  0.94  0.87
      4       1.49  0.33  2.52  0.65  0.21  0.11  1.10  0.54  0.48  0.49
      5       0.99  0.54  0.76  0.21  0.17  0.21  0.34  0.19  0.38  0.94
      6       1.18  0.41  1.67  0.59  0.27  0.25  0.74  0.53  0.61  1.08
50    2       0.36  0.46  0.93  0.39  0.15  0.19  0.39  0.39  0.36  0.86
      3       0.67  0.50  2.70  0.56  0.34  0.28  1.19  0.53  0.77  1.19
      4       1.75  0.27  2.23  1.07  0.37  0.22  1.15  0.92  0.82  0.99
      5       1.24  0.43  1.91  0.67  0.45  0.28  0.85  0.58  1.01  1.26
      6       2.60  0.32  3.23  2.53  0.33  0.20  1.44  2.25  0.70  0.89
100   2       0.74  0.25  2.76  0.74  0.40  0.18  1.36  0.68  0.89  0.80
      3       1.68  0.19  2.10  1.36  0.26  0.11  0.94  1.22  0.58  0.49
      4       1.30  0.18  2.03  1.88  0.24  0.11  0.93  1.68  0.53  0.44
      5       2.79  0.20  3.86  1.39  0.41  0.14  1.72  1.24  0.92  0.64
      6       1.46  0.15  1.67  1.97  0.45  0.15  0.74  1.76  1.01  0.71
200   2       1.79  0.12  2.12  2.30  0.20  0.08  0.95  2.05  0.44  0.37
      3       1.15  0.19  3.27  1.54  0.26  0.11  1.47  1.38  0.59  0.49
      4       1.61  0.21  2.71  2.09  0.31  0.18  1.21  1.82  0.69  0.80
      5       3.38  0.19  1.57  0.89  0.43  0.18  0.70  0.80  0.97  0.79
      6       5.39  0.19  1.25  1.70  0.32  0.18  0.56  1.52  0.70  0.78
400   2       1.02  0.14  1.95  1.26  0.19  0.06  0.89  1.12  0.42  0.28
      3       1.75  0.17  1.67  1.66  0.36  0.13  0.75  1.48  0.81  0.57
      4       2.01  0.17  3.61  1.85  0.37  0.12  1.61  1.66  0.82  0.56
      5       3.27  0.23  1.06  1.24  0.47  0.21  0.47  1.11  1.06  0.95
      6       4.46  0.30  1.34  1.22  0.41  0.17  0.60  1.09  0.91  0.75

              rev1  rev2  rev5  rev10
ntree ndepth
25    2       0.97  1.02  0.85   0.78
      3       0.42  1.04  1.08   1.47
      4       1.44  1.38  0.98   1.75
      5       0.55  0.74  1.34   1.82
      6       1.19  0.86  1.31   1.87
50    2       1.61  0.95  1.09   2.00
      3       2.19  1.32  1.22   1.78
      4       2.93  1.18  1.74   1.34
      5       2.49  1.58  1.91   1.28
      6       2.62  1.96  1.07   0.94
100   2       1.92  0.94  1.24   1.17
      3       2.04  0.89  1.22   1.06
      4       2.63  1.41  0.80   0.92
      5       2.29  1.26  1.85   0.74
      6       2.85  1.67  1.27   1.51
200   2       2.18  1.69  0.53   0.72
      3       1.72  1.38  1.42   0.95
      4       2.30  2.41  1.34   2.02
      5       4.20  2.24  1.70   1.38
      6       4.81  1.87  1.51   1.61
400   2       3.52  0.77  1.63   1.09
      3       3.04  2.60  1.76   1.35
      4       3.08  2.56  1.66   1.54
      5       3.83  1.43  2.32   2.03
      6       5.15  2.95  0.95   1.64

In [23]:
def draw_without_stdev(measure, indices, pos):
    g = df.groupby(['ndim'])[measure].apply(lambda x: np.mean(x))
    for idx in g.index:
        print(f'({idx}, {round(g.loc[idx][0]*100, 2)})')
              
def draw_with_stdev(measure, indices, pos):
    g = df.groupby(['ndim'])[measure].apply(lambda x: (np.mean(x), np.std(x)))
    for idx in g.index:
        print(f'({idx}, {round(g.loc[idx][0]*100, 2)}) +- ({round(g.loc[idx][1]*100, 2)}, {round(g.loc[idx][1]*100, 2)})')

In [24]:
# Precision
draw_with_stdev('pr1')
draw_with_stdev('pr2')
draw_with_stdev('pr5')
draw_with_stdev('pr10')

(25, 86.24) +- (2.52, 2.52)
(50, 90.51) +- (2.23, 2.23)
(100, 93.13) +- (2.03, 2.03)
(200, 93.62) +- (2.71, 2.71)
(400, 94.77) +- (3.61, 3.61)
(25, 49.6) +- (0.65, 0.65)
(50, 66.71) +- (1.07, 1.07)
(100, 80.79) +- (1.88, 1.88)
(200, 79.31) +- (2.09, 2.09)
(400, 79.34) +- (1.85, 1.85)
(25, 22.72) +- (0.21, 0.21)
(50, 30.38) +- (0.37, 0.37)
(100, 38.67) +- (0.24, 0.24)
(200, 37.74) +- (0.31, 0.31)
(400, 37.64) +- (0.37, 0.37)
(25, 12.71) +- (0.11, 0.11)
(50, 16.45) +- (0.22, 0.22)
(100, 20.22) +- (0.11, 0.11)
(200, 19.89) +- (0.18, 0.18)
(400, 19.97) +- (0.12, 0.12)

In [20]:
# Revenue
draw_with_stdev('rev1')
draw_with_stdev('rev2')
draw_with_stdev('rev5')
draw_with_stdev('rev10')

(25, 31.25) +- (1.44, 1.44)
(50, 42.71) +- (2.93, 2.93)
(100, 44.84) +- (2.63, 2.63)
(200, 40.65) +- (2.3, 2.3)
(400, 38.25) +- (3.08, 3.08)
(25, 40.65) +- (1.38, 1.38)
(50, 61.25) +- (1.18, 1.18)
(100, 66.31) +- (1.41, 1.41)
(200, 63.89) +- (2.41, 2.41)
(400, 63.03) +- (2.56, 2.56)
(25, 50.48) +- (0.98, 0.98)
(50, 74.07) +- (1.74, 1.74)
(100, 83.45) +- (0.8, 0.8)
(200, 78.19) +- (1.34, 1.34)
(400, 77.75) +- (1.66, 1.66)
(25, 60.9) +- (1.75, 1.75)
(50, 80.58) +- (1.34, 1.34)
(100, 89.3) +- (0.92, 0.92)
(200, 84.15) +- (2.02, 2.02)
(400, 84.58) +- (1.54, 1.54)